Example that creates a NL file from a Pyomo model and use the generated NL file to obtain a `NLPModel`
PythonOptimizers/NLP.py pull request #82
Opened 2017-04-10 20:42 UTC by syarra

2017-04-11 04:57 UTC, dpo commented
Thanks. Are you able to pass the model to a solver?

2017-04-20 20:03 UTC, syarra commented
I updated the examples and one problem is solved using TRON.

2017-04-20 22:00 UTC, dpo requested changes

2017-04-20 22:00 UTC, dpo commented on .travis.yml
>    - brew install adol-c
You really need `-f` here.

2017-04-20 22:00 UTC, dpo commented on .travis.yml
> +  -
What's this?

2017-04-20 22:00 UTC, dpo commented on examples/demo_pyomo.py
> +    display_model(simple_model)
It seems much simpler to just call [`display_basic_info()`](https://github.com/PythonOptimizers/NLP.py/blob/develop/nlp/model/nlpmodel.py#L687).

2017-04-20 22:00 UTC, dpo commented on examples/demo_pyomo.py
> +    display_model(rosenbrock_model)
Let use just one model instead of two. It doesn't add anything new.

2017-04-20 22:00 UTC, dpo commented on nlp/optimize/tron.py
> +            H = model.hop(self.x.copy())
Does this wreck AugLag?!

2017-04-20 22:00 UTC, dpo commented on examples/demo_pyomo.py
> +    _, smap_id = model.write(nl_filename,
The `write_nl()` function doesn't really simplify anything. I suggest to remove it and call `model.write()` directly.

2017-04-20 22:00 UTC, dpo commented on examples/demo_pyomo.py
> +    return model
Let's remove this model.

2017-05-15 21:50 UTC, dpo approved these changes

2017-05-15 21:51 UTC, merged